version: 0.2
env:
  secrets-manager:
    TOKEN: firstSecret:tokenforsonar
    SNYK_TOKEN: snykSecret:tokenforsnyk

phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - apt-get update && apt-get -y install wget default-jdk maven
  build:
    commands:
      # Static Application Security Scan (SAST scan) using SonarCloud
      - mvn verify sonar:sonar -Dsonar.projectKey=awsdevsecjavaproject -Dsonar.organization=awsdevsecjavaproject -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN

      # Software Composition Analysis Scan (SCA scan) using Snyk
      - mvn snyk:test -fn

      # Dynamic Application Security Scan (DAST scan) using OWASP ZAP
      - wget https://github.com/zaproxy/zaproxy/releases/tag/v2.16.0/ZAP_2.16.0_Linux.tar.gz
      - tar -xvf ZAP_2.16.0_Linux.tar.gz
      - cd ZAP_2.16.0*
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

artifacts:
  files:
    - zap_report.html
